import lazy_import

lazy_import.lazy_module("tkinter")
lazy_import.lazy_module("tkinter.filedialog")
lazy_import.lazy_module("tkinter.messagebox")
lazy_import.lazy_module("tkinter.simpledialog")
lazy_import.lazy_module("tkinter.ttk")
lazy_import.lazy_module("tkinter.font")
lazy_import.lazy_module("tkinter.colorchooser")
lazy_import.lazy_module("tkinter.scrolledtext")
lazy_import.lazy_module("idlelib.percolator")
lazy_import.lazy_module("idlelib.colorizer")
lazy_import.lazy_module("textblob")
lazy_import.lazy_module("time")
lazy_import.lazy_module("readtime")
lazy_import.lazy_module("os")
lazy_import.lazy_module("webbrowser")